GET http://localhost:3000/api/users 

###

POST http://localhost:3000/api/users 
Content-Type: application/json

{
    "username": "Federico",
    "email": "fede@gmail.com",
    "password": "12345"
}

###

PUT http://localhost:3000/api/users/62cbdf73fa64075b82f23323/product/62c7e621d41732983f8b71df